### ISSUE TITLE
[docs] Docs page without a h2 doesn't work

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/electric#27]
Something like that works:

```
<article id="introduction">
## Intro

Trabalhar remotamente vem se tornando cada vez mais um objetivo de todos os trabalhadores na área de TI ao redor do mundo. Estar alinhado com suas necessidades...
</article>
```

If I remove `## Intro` it duplicates the content.

**Comment by Robert-Frampton** [comment]
Hey @pragmaticivan 

Looks like the error is coming from https://github.com/metal/metal-reading-progress. The problem is that it's trying to find a title from the `<section>` tag, but it doesn't fail gracefully.

If you want to use `<section>` tags without the reading progress trying to use them, you can just set the `articleSelector` attribute of the `ElectricReadingProgress` component that's being rendered in the layout to be more specific.

I'm going to close this and open an issue on the metal-reading-progress repo.

**Comment by pragmaticivan** [comment]
Thanks @Robert-Frampton
